knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration

#        oe_modules_oauth:
#            type: generic
#            provider_class: App\Security\OauthProvider\OeModules
#            # optional: a class that extends OAuth2Client
#            # client_class: Some\Custom\Client
#
#            # optional: if your provider has custom constructor options
#            # provider_options: {}
#
#            # now, all the normal options!
#            client_id: '%env(OAUTH_OEMODULES_CLIENT_ID)%'
#            client_secret: '%env(OAUTH_OEMODULES_CLIENT_SECRET)%'
#            redirect_route: connect_oemodules_check
#            redirect_params: { }
#            # whether to check OAuth2 "state": defaults to true
#            # use_state: true
