when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            environment: '%kernel.environment%'
            sample_rate: 0.1
            traces_sample_rate: 0.1
            server_name: "marketplace.oe-modules.com"
            send_attempts: 4
            release: '%release.version%'

        tracing:
            enabled: true
            dbal: # DB queries
                enabled: true
            cache:
                enabled: true
            twig: # templating engine
                enabled: true

        #        If you are using Monolog, you also need this additional configuration to log the errors correctly:
        #        https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
        register_error_listener: false
        register_error_handler: false

    monolog:
        handlers:
            sentry:
                type: sentry
                level: !php/const Monolog\Logger::ERROR
                hub_id: Sentry\State\HubInterface


