twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        # directories are relative to the project root dir (but you
        # can also use absolute directories)
        '_catalog/src/Adapter/Http/Templates': 'catalog'

    globals:
        release_version: '%release.version%'


when@test:
    twig:
        strict_variables: true
