twig:
    file_name_pattern: '*.twig'

    paths:
        # directories are relative to the project root dir (but you
        # can also use absolute directories)
        '_bffWeb/src/Infrastructure/Templates': 'web'

    globals:
        release_version: '%release.version%'
        google_site_verification: ''

    form_themes: ['bootstrap_5_layout.html.twig']

when@prod:
    twig:
        globals:
            google_site_verification: "xIV2mRpvLGP9emiCI8zJeZNqq_H-g05yUgMxfm81RWA"


when@test:
    twig:
        strict_variables: true
