webfactory_piwik:
  # Required, no default. Must be set to the site id found in the Matomo control panel
  site_id: 2
  # Required. no default. Hostname and path to the Matomo host.
  piwik_host: matomo.oe-modules.com
  # Optional, has default. Usually, you only want to include the tracking code in a production environment
  disabled: '%kernel.debug%'
  # Optional, has default. Path to the tracking script on the host.
  tracker_path: "/js/"
  # Optional, has default. Disable cookies in favor of GDPR
  # https://matomo.org/faq/new-to-piwik/how-do-i-use-matomo-analytics-without-consent-or-cookie-banner/ & https://matomo.org/faq/general/faq_157/
  disable_cookies: true


when@prod:
  webfactory_piwik:
    disabled: false

when@dev:
  webfactory_piwik:
    disabled: true

when@test:
  webfactory_piwik:
    disabled: true
