controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

bff_web_controllers:
    resource:
        path: ../context/bffWeb/src/AdapterForWeb
        namespace: BffWeb\AdapterForWeb
    type: attribute

bff_api_controllers:
    resource:
        path: ../context/bffApi/src/AdapterForApi
        namespace: BffApi\AdapterForApi
    type: attribute
