controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

webapi_controllers:
    resource:
        path: ../src/Adapter/Http/WebApi
        namespace: App\Adapter\Http\WebApi
    type: attribute
