controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

catalog_web_controllers:
    resource:
        path: ../_catalog/src/Adapter/Http/Web
        namespace: Catalog\Adapter\Http\Web
    type: attribute

catalog_webapi_controllers:
    resource:
        path: ../_catalog/src/Adapter/Http/WebApi
        namespace: Catalog\Adapter\Http\WebApi
    type: attribute

bff_web_controllers:
    resource:
        path: ../_bffWeb/src/AdapterForWeb
        namespace: BffWeb\AdapterForWeb
    type: attribute
