framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths:
            - '%kernel.project_dir%/_catalog/src/Infrastructure/Translations'
        fallbacks:
            - '%locale%'
        providers:
