# ... previous config options...

comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment

component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: module_bff_api
      name: BffApi
      paths:
        - context/bffApi/**
    - component_id: module_bff_web
      name: BffWeb
      paths:
        - context/bffWeb/**
    - component_id: module_catalog  # this is an identifier that should not be changed
      name: Catalog  # this is a display name, and can be changed freely
      paths:
        - context/catalog/**
    - component_id: module_metadata
      name: Metadata
      paths:
        - context/metadata/**
#    - component_id: module_core
#      name: core
#      paths:
#        - core/**
#      statuses:           # the core component has its own statuses
#        - type: project
#          target: auto
#        - type: patch
#    - component_id: ascii
#      paths:
#        - .*/ascii.py
#    - component_id: emoji
#      paths:
#        - .*/emoji.py
