name: CD/CI

on: [ push ]

jobs:
  commit-stage-workflow:
    name: Commit Stage
    uses: medicalmundi/marketplace-engine/.github/workflows/commit-stage.yaml@main
    with:
      triggering-sha: "${{ github.sha }}"


  acceptance-stage-workflow:
    name: Commit Stage
    needs:
      - commit-stage-workflow
    uses: medicalmundi/marketplace-engine/.github/workflows/acceptance-stage.yaml@main
    with:
      triggering-sha: "${{ github.sha }}"


  deploy-on-stage-workflow:
    name: Deploy on Staging server
    if: (${{ vars.ENABLE_DEPLOY_ON_STAGING  == '1' }}) & (${{ github.ref_name == 'main' }})
    needs:
      - acceptance-stage-workflow
    secrets: inherit
    uses: medicalmundi/marketplace-engine/.github/workflows/deploy-on-staging.yaml@main
    with:
      triggering-sha: "${{ github.sha }}"
